/// WARNING DO NOT EDIT THIS FILE, IT IS CODE-GENERATED!!!
/// WARNING DO NOT EDIT THIS FILE, IT IS CODE-GENERATED!!!
/// WARNING DO NOT EDIT THIS FILE, IT IS CODE-GENERATED!!!

let operator_constructors = { 
  
  "ceil": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"ceil", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fastpow": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fastpow", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "mul": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"mul", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.product" }
    ]`);
  },
  "fold": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fold", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.min" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.max" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "rdiv": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"rdiv", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.quotient" }
    ]`);
  },
  "min": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"min", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "mix": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"mix", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.loval" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.hival" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.interp" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "cartopol": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"cartopol", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.x" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.y" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.distance" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.angle" }
    ]`);
  },
  "tanh": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"tanh", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "scale": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"scale", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.ilo" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.ihi" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.olo" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.ohi" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.exp" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "eqp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"eqp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "sin": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sin", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "exp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"exp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "eq": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"eq", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "exp2": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"exp2", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "ltep": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"ltep", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "poltocar": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"poltocar", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.r" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.theta" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.x" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.y" }
    ]`);
  },
  "fract": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fract", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.fract" }
    ]`);
  },
  "sqrt": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sqrt", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "radians": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"radians", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.degrees" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "neqp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"neqp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "atan": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"atan", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "mod": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"mod", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.modulo" }
    ]`);
  },
  "atanh": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"atanh", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fastexp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fastexp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "sinh": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sinh", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "acos": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"acos", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "rmod": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"rmod", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.modulo" }
    ]`);
  },
  "sub": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sub", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.difference" }
    ]`);
  },
  "neq": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"neq", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "ltp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"ltp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "bool": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"bool", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.bool" }
    ]`);
  },
  "add": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"add", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.sum" }
    ]`);
  },
  "max": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"max", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "hypot": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"hypot", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.x" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.y" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "floor": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"floor", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "abs": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"abs", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.abs" }
    ]`);
  },
  "absdiff": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"absdiff", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.abs-diff" }
    ]`);
  },
  "log2": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"log2", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "degrees": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"degrees", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.radians" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "selector": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"selector", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}...." },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "switch": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"switch", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.condition" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.iftrue" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.iffalse" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "cosh": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"cosh", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "out": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"out", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" }
    ]`);
  },
  "wrap": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"wrap", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.min" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.max" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "smoothstep": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"smoothstep", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.loval" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.hival" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.interp" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "acosh": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"acosh", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "step": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"step", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "gtep": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"gtep", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "or": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"or", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fastsin": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fastsin", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fastcos": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fastcos", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "sign": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sign", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "log10": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"log10", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "log": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"log", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "lte": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"lte", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "gte": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"gte", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "asinh": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"asinh", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "clamp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"clamp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.min" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.max" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.clamped" }
    ]`);
  },
  "noise": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"noise", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"outlet", "path":"${path}.random-stream" }
    ]`);
  },
  "pow": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"pow", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fasttan": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fasttan", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "lt": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"lt", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "and": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"and", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "div": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"div", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.quotient" }
    ]`);
  },
  "xor": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"xor", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "atan2": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"atan2", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.opposite" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.adjacent" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "gt": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"gt", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "gtp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"gtp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "not": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"not", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "pass": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"pass", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "asin": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"asin", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "rsub": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"rsub", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value1" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.difference" }
    ]`);
  },
  "tan": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"tan", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "trunc": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"trunc", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "cos": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"cos", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "neg": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"neg", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "rate": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"rate", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.phase" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.multiplier" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "ftom": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"ftom", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.freq" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.tuning" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "sah": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sah", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.control" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.thresh" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "counter": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"counter", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.incr" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.reset" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.max" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out2" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out3" }
    ]`);
  },
  "sampstoms": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"sampstoms", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.period" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "train": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"train", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.period" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.width" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.onset" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "dbtoa": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"dbtoa", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.db" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "latch": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"latch", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.control" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "mulequals": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"mulequals", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.incr" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.reset" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "elapsed": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"elapsed", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "change": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"change", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "triangle": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"triangle", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.phase" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.duty" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "phasewrap": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"phasewrap", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.phase" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "mtof": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"mtof", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.note" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.tuning" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "isnan": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"isnan", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "t60time": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"t60time", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.multiplier" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "delta": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"delta", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "history": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"history", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.value" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "t60": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"t60", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.time" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "plusequals": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"plusequals", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.incr" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.reset" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fixnan": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fixnan", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "mstosamps": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"mstosamps", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.period" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "round": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"round", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.base" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "interp": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"interp", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.t" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.a" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.b" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "slide": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"slide", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.up" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.down" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "atodb": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"atodb", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.amplitude" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "cycle": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"cycle", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.freq" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out2" }
    ]`);
  },
  "dcblock": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"dcblock", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "phasor": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"phasor", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.freq" },
      { "op":"newnode", "kind":"inlet", "path":"${path}.reset" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "isdenorm": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"isdenorm", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  },
  "fixdenorm": function(path) { 
    return JSON.parse(`[
      { "op":"newnode", "path":"${path}", "kind":"fixdenorm", "category":"operator", "pos":[0,0,0], "orient":[0,0,0,1] },
      { "op":"newnode", "kind":"inlet", "path":"${path}.input" },
      { "op":"newnode", "kind":"outlet", "path":"${path}.out1" }
    ]`);
  }
}

let module_constructors = {
	"sample_and_hold": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "sample_and_hold",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.signal",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.trigger",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.threshold",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.out",
				"kind": "inlet"
			}
		]`);
    },

	"freevoib": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "freevoib",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.signal",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.feedback_1",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0.9,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.feedback_2",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0.5,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.damping",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0.5,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.spread",
				"kind": "small_knob",
				"range": [
					0,
					400
				],
				"taper": "linear",
				"value": 100,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.out",
				"kind": "outlet"
			}
		]`);
    },

	"shifter": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "shifter",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.signal",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.range",
				"kind": "small_knob"
			},
			{
				"op": "newnode",
				"path": "${path}.out",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.>",
				"kind": "outlet"
			}
		]`);
    },

	"constant": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "constant",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.voltage",
				"kind": "large_knob"
			},
			{
				"op": "newnode",
				"path": "${path}.out",
				"kind": "outlet"
			}
		]`);
    },

	"lfo": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "lfo",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.fm_cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.phasor_sync",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.pulse_width_cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.rate",
				"kind": "large_knob",
				"range": [
					0,
					80
				],
				"taper": "log 3.8",
				"value": 0.63,
				"unit": "Hz"
			},
			{
				"op": "newnode",
				"path": "${path}.index",
				"kind": "small_knob",
				"range": [
					0,
					10
				],
				"taper": "linear",
				"value": 1,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.pulse_width",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0.25,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.onset",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.sine",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.phasor",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.pulse",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.sine_index",
				"kind": "outlet"
			}
		]`);
    },

	"dualvco": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "dualvco",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.vco_1_cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.index_cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_2_cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.feedback_cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_1_rate",
				"kind": "large_knob",
				"range": [
					0,
					6000
				],
				"taper": "log 3.8",
				"value": 120,
				"unit": "Hz"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_1_waveform",
				"kind": "n_switch",
				"throws": [
					"Sine",
					"Phasor",
					"Triangle"
				],
				"value": "Sine"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_2_rate",
				"kind": "large_knob",
				"range": [
					0,
					6000
				],
				"taper": "log 3.8",
				"value": 3,
				"unit": "Hz"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_2_waveform",
				"kind": "n_switch",
				"throws": [
					"Sine",
					"Phasor",
					"Triangle"
				],
				"value": "Sine"
			},
			{
				"op": "newnode",
				"path": "${path}.feedback",
				"kind": "small_knob",
				"range": [
					0,
					6
				],
				"taper": "linear",
				"value": 0.25,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_1",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.vco_2",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.master",
				"kind": "outlet"
			}
		]`);
    },

	"vca": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "vca",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.signal",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.cv",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.cv_amount",
				"kind": "large_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0.5,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.bias",
				"kind": "large_knob",
				"range": [
					0,
					1
				],
				"taper": "linear",
				"value": 0.5,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.output",
				"kind": "outlet"
			}
		]`);
    },

	"comparator": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "comparator",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.A",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.B",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.max",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.min",
				"kind": "outlet"
			}
		]`);
    },

	"outs": function(path) { 
    return JSON.parse(`[
			{
				"op": "newnode",
				"path": "${path}",
				"kind": "outs",
				"category": "abstraction",
				"pos": [
					0,
					0,
					0
				],
				"orient": [
					0,
					0,
					0,
					1
				]
			},
			{
				"op": "newnode",
				"path": "${path}.left_(mono)",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.right_(stereo)",
				"kind": "inlet"
			},
			{
				"op": "newnode",
				"path": "${path}.volume",
				"kind": "small_knob",
				"range": [
					0,
					1
				],
				"taper": "log 3.8",
				"value": 0.25,
				"unit": "float"
			},
			{
				"op": "newnode",
				"path": "${path}.left",
				"kind": "outlet"
			},
			{
				"op": "newnode",
				"path": "${path}.right",
				"kind": "outlet"
			}
		]`);
    },
}

let operator_names = Object.keys(operator_constructors)
let module_names = Object.keys(module_constructors)

function spawnRandomModule(pos, orient) {
  let opname, ctor
  if (Math.random() < 0.5) {
    opname = module_names[Math.floor(Math.random() * module_names.length)]
    ctor = module_constructors[opname]
  } else {
    opname = operator_names[Math.floor(Math.random() * module_names.length)]
    ctor = operator_constructors[opname]
  }
  let path = gensym(opname)
  let deltas = ctor(path);
  deltas[0].pos = pos;
  deltas[0].orient = orient;
  return deltas; 
}
