let tempScene = {
    "metadata": {
        "version": 4.5,
        "type": "Object",
        "generator": "Object3D.toJSON"
    },
    "geometries": [
        {
            "uuid": "dc9c8a06-8ac9-4234-9f88-836249b02e72",
            "type": "BufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            0,
                            0,
                            -45,
                            -1
                        ],
                        "normalized": false
                    }
                },
                "boundingSphere": {
                    "center": [
                        0,
                        -22.5,
                        -0.5
                    ],
                    "radius": 22.5055548698538
                }
            }
        },
        {
            "uuid": "c29bbf60-b92a-48c4-8e8a-c2830a5976c2",
            "type": "BufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            0,
                            0,
                            -45,
                            -1
                        ],
                        "normalized": false
                    }
                },
                "boundingSphere": {
                    "center": [
                        0,
                        -22.5,
                        -0.5
                    ],
                    "radius": 22.5055548698538
                }
            }
        },
        {
            "uuid": "29efb315-41ea-4844-95cf-c99b511a2ef6",
            "type": "BoxGeometry",
            "width": 1,
            "height": 2,
            "depth": 0.3,
            "widthSegments": 1,
            "heightSegments": 1,
            "depthSegments": 1
        },
        {
            "uuid": "f8635ccd-1042-4638-8507-491788b9d4eb",
            "type": "CylinderGeometry",
            "radiusTop": 0.2,
            "radiusBottom": 0.2,
            "height": 0.1,
            "radialSegments": 50,
            "heightSegments": 1,
            "openEnded": false,
            "thetaStart": 0,
            "thetaLength": 6.283185307179586
        },
        {
            "uuid": "9f067fb4-e2b1-4591-9c34-7d0b4dca72bd",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    },
                    "aTroikaGlyphBounds": {
                        "itemSize": 4,
                        "type": "Float32Array",
                        "array": [
                            0.0029403686057776213,
                            -0.19520416855812073,
                            0.10555572807788849,
                            -0.07022552192211151,
                            0.11177673190832138,
                            -0.19818420708179474,
                            0.22259826958179474,
                            -0.02486267127096653,
                            0.2225692719221115,
                            -0.19520416855812073,
                            0.3219619691371918,
                            -0.07022552192211151,
                            0.3253036439418793,
                            -0.19520416855812073,
                            0.4369033873081207,
                            -0.07022552192211151,
                            0.44287109375,
                            -0.19609375298023224,
                            0.4820312559604645,
                            -0.02500000037252903,
                            0.4924331605434418,
                            -0.19506683945655823,
                            0.5907699465751648,
                            -0.07231597602367401,
                            0.5884857177734375,
                            -0.19686584174633026,
                            0.6647369265556335,
                            -0.04493103176355362,
                            0.6636825799942017,
                            -0.19520416855812073,
                            0.7687393426895142,
                            -0.07022552192211151,
                            0.8135666251182556,
                            -0.19297638535499573,
                            0.9183670282363892,
                            -0.07245330512523651,
                            0.9161239266395569,
                            -0.19520416855812073,
                            1.0187393426895142,
                            -0.07022552192211151,
                            1.0266602039337158,
                            -0.19609375298023224,
                            1.065820336341858,
                            -0.02500000037252903,
                            1.0762221813201904,
                            -0.19506683945655823,
                            1.1745589971542358,
                            -0.07231597602367401,
                            1.18213951587677,
                            -0.19520416855812073,
                            1.2871962785720825,
                            -0.07022552192211151,
                            1.3374130725860596,
                            -0.19520416855812073,
                            1.4490127563476562,
                            -0.07022552192211151,
                            1.4454612731933594,
                            -0.1962379515171051,
                            1.5307105779647827,
                            -0.022805023938417435,
                            1.5728729963302612,
                            -0.19568176567554474,
                            1.6145294904708862,
                            -0.03127136081457138,
                            1.6238784790039062,
                            -0.19311371445655823,
                            1.72211754322052,
                            -0.07036285102367401,
                            1.7313735485076904,
                            -0.23659515380859375,
                            1.8414779901504517,
                            -0.06750641018152237,
                            1.8460464477539062,
                            -0.19506683945655823,
                            1.9443832635879517,
                            -0.07231597602367401,
                            1.9420989751815796,
                            -0.19686584174633026,
                            2.018350124359131,
                            -0.04493103176355362
                        ],
                        "normalized": false,
                        "meshPerAttribute": 1,
                        "isInstancedBufferAttribute": true
                    },
                    "aTroikaGlyphIndex": {
                        "itemSize": 1,
                        "type": "Uint16Array",
                        "array": [
                            0,
                            1,
                            2,
                            7,
                            4,
                            5,
                            8,
                            6,
                            3,
                            0,
                            4,
                            5,
                            6,
                            7,
                            9,
                            10,
                            11,
                            12,
                            5,
                            8
                        ],
                        "normalized": false,
                        "meshPerAttribute": 1,
                        "isInstancedBufferAttribute": true
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        1.0079589843750003,
                        -0.1171875,
                        0
                    ],
                    "radius": 1.0147483551790228
                }
            },
            "instanceCount": 20,
            "isInstancedBufferGeometry": true
        },
        {
            "uuid": "46afae36-56a4-4a61-86dd-419419e50f79",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    },
                    "aTroikaGlyphBounds": {
                        "itemSize": 4,
                        "type": "Float32Array",
                        "array": [
                            -0.15912017226219177,
                            -0.19520416855812073,
                            -0.05650481954216957,
                            -0.07022552192211151,
                            -0.05028381198644638,
                            -0.19818420708179474,
                            0.06053772196173668,
                            -0.02486267127096653,
                            0.06050872802734375,
                            -0.19520416855812073,
                            0.159901425242424,
                            -0.07022552192211151
                        ],
                        "normalized": false,
                        "meshPerAttribute": 1,
                        "isInstancedBufferAttribute": true
                    },
                    "aTroikaGlyphIndex": {
                        "itemSize": 1,
                        "type": "Uint16Array",
                        "array": [
                            0,
                            1,
                            2
                        ],
                        "normalized": false,
                        "meshPerAttribute": 1,
                        "isInstancedBufferAttribute": true
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        0,
                        -0.1171875,
                        0
                    ],
                    "radius": 0.19999132733614747
                }
            },
            "instanceCount": 3,
            "isInstancedBufferGeometry": true
        },
        {
            "uuid": "d0815fe2-e5b5-467f-855a-3cbea2f52510",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    },
                    "aTroikaGlyphBounds": {
                        "itemSize": 4,
                        "type": "Float32Array",
                        "array": [
                            -0.23867951333522797,
                            -0.19297638535499573,
                            -0.13387909531593323,
                            -0.07245330512523651,
                            -0.13612212240695953,
                            -0.19520416855812073,
                            -0.03350676968693733,
                            -0.07022552192211151,
                            -0.02558593824505806,
                            -0.19609375298023224,
                            0.01357421837747097,
                            -0.02500000037252903,
                            0.02397613599896431,
                            -0.19506683945655823,
                            0.12231292575597763,
                            -0.07231597602367401,
                            0.129893496632576,
                            -0.19520416855812073,
                            0.2349502593278885,
                            -0.07022552192211151
                        ],
                        "normalized": false,
                        "meshPerAttribute": 1,
                        "isInstancedBufferAttribute": true
                    },
                    "aTroikaGlyphIndex": {
                        "itemSize": 1,
                        "type": "Uint16Array",
                        "array": [
                            3,
                            0,
                            4,
                            5,
                            6
                        ],
                        "normalized": false,
                        "meshPerAttribute": 1,
                        "isInstancedBufferAttribute": true
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        0,
                        -0.1171875,
                        0
                    ],
                    "radius": 0.2621265661568485
                }
            },
            "instanceCount": 5,
            "isInstancedBufferGeometry": true
        },
        {
            "uuid": "367a7558-8a0f-4caa-b365-e9488ef14225",
            "type": "BoxGeometry",
            "width": 2,
            "height": 2,
            "depth": 0.3,
            "widthSegments": 1,
            "heightSegments": 1,
            "depthSegments": 1
        },
        {
            "uuid": "5e6bf299-2c64-420c-90c8-5dbda5c5b963",
            "type": "CylinderGeometry",
            "radiusTop": 0.2,
            "radiusBottom": 0.2,
            "height": 0.1,
            "radialSegments": 50,
            "heightSegments": 1,
            "openEnded": false,
            "thetaStart": 0,
            "thetaLength": 6.283185307179586
        },
        {
            "uuid": "0bb8aee8-ce7c-49cb-b78b-6bff7cd3458a",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        0,
                        0,
                        0
                    ],
                    "radius": -1
                }
            },
            "instanceCount": null,
            "isInstancedBufferGeometry": true
        },
        {
            "uuid": "43598099-f831-47b6-aac0-e61a141feb26",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        0,
                        0,
                        0
                    ],
                    "radius": -1
                }
            },
            "instanceCount": null,
            "isInstancedBufferGeometry": true
        },
        {
            "uuid": "7896c38a-10bc-469b-8f15-f29948b1a3a6",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        0,
                        0,
                        0
                    ],
                    "radius": -1
                }
            },
            "instanceCount": null,
            "isInstancedBufferGeometry": true
        },
        {
            "uuid": "4cc631bb-9753-41af-bbc0-b74af65ea29e",
            "type": "InstancedBufferGeometry",
            "data": {
                "attributes": {
                    "position": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            0,
                            1,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            0
                        ],
                        "normalized": false
                    },
                    "normal": {
                        "itemSize": 3,
                        "type": "Float32Array",
                        "array": [
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1,
                            0,
                            0,
                            -1
                        ],
                        "normalized": false
                    },
                    "uv": {
                        "itemSize": 2,
                        "type": "Float32Array",
                        "array": [
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1,
                            1,
                            1,
                            0,
                            0,
                            1,
                            0
                        ],
                        "normalized": false
                    }
                },
                "index": {
                    "type": "Uint16Array",
                    "array": [
                        0,
                        2,
                        1,
                        2,
                        3,
                        1,
                        4,
                        6,
                        5,
                        6,
                        7,
                        5
                    ]
                },
                "groups": [
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 0
                    },
                    {
                        "start": 0,
                        "count": null,
                        "materialIndex": 1
                    }
                ],
                "boundingSphere": {
                    "center": [
                        0,
                        0,
                        0
                    ],
                    "radius": -1
                }
            },
            "instanceCount": null,
            "isInstancedBufferGeometry": true
        }
    ],
    "materials": [
        {
            "uuid": "f8d0da6c-82bb-48df-abfc-e6e5dfc33ad5",
            "type": "LineBasicMaterial",
            "color": 16777215,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "linewidth": 20
        },
        {
            "uuid": "3420e75b-2820-448d-8170-a8b7d0e32ad2",
            "type": "LineBasicMaterial",
            "color": 16777215,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "linewidth": 20
        },
        {
            "uuid": "7ba73866-bc1c-48e9-aebc-21b8fa612eac",
            "type": "MeshStandardMaterial",
            "color": 11674146,
            "roughness": 1,
            "metalness": 0,
            "emissive": 0,
            "envMapIntensity": 1,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "flatShading": true
        },
        {
            "uuid": "48a45bfd-b4e4-40fb-9396-956c6a0ef0a2",
            "type": "MeshStandardMaterial",
            "color": 3100495,
            "roughness": 1,
            "metalness": 0,
            "emissive": 0,
            "envMapIntensity": 1,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "flatShading": true
        },
        {
            "uuid": "6C043312-8E09-4672-A15C-3F7098B184CE",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        },
        {
            "uuid": "87BCF4B6-D465-4B74-9A16-A7CF3D784EA4",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        },
        {
            "uuid": "2b1cbc01-97cc-44e1-8ab6-a88570b0435c",
            "type": "MeshStandardMaterial",
            "color": 8900331,
            "roughness": 1,
            "metalness": 0,
            "emissive": 0,
            "envMapIntensity": 1,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "flatShading": true
        },
        {
            "uuid": "7F3CEF16-9F08-4347-A958-006449873B87",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        },
        {
            "uuid": "2f80f1ec-2a97-45b0-ac04-992a14082790",
            "type": "MeshStandardMaterial",
            "color": 11674146,
            "roughness": 1,
            "metalness": 0,
            "emissive": 0,
            "envMapIntensity": 1,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "flatShading": true
        },
        {
            "uuid": "3b9f8eb9-1ce8-4b34-9d0d-ec23b21e834e",
            "type": "MeshStandardMaterial",
            "color": 3100495,
            "roughness": 1,
            "metalness": 0,
            "emissive": 0,
            "envMapIntensity": 1,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "flatShading": true
        },
        {
            "uuid": "4F801CB1-6F1F-4E17-A118-2AB694878A6B",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        },
        {
            "uuid": "475F0F94-92B9-4F42-BC6E-B7C81A528287",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        },
        {
            "uuid": "14fb8b30-e1f6-4ed1-8b44-a0a4ecd13483",
            "type": "MeshStandardMaterial",
            "color": 8900331,
            "roughness": 1,
            "metalness": 0,
            "emissive": 0,
            "envMapIntensity": 1,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680,
            "flatShading": true
        },
        {
            "uuid": "F8882FE7-ADD4-467F-80D4-BDD8076E97A3",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        },
        {
            "uuid": "A5A05BD6-9E40-4650-AA27-35734D3DE985",
            "type": "MeshBasicMaterial",
            "color": 16777215,
            "reflectivity": 1,
            "refractionRatio": 0.98,
            "shadowSide": 2,
            "side": 2,
            "transparent": true,
            "depthFunc": 3,
            "depthTest": true,
            "depthWrite": true,
            "colorWrite": true,
            "stencilWrite": false,
            "stencilWriteMask": 255,
            "stencilFunc": 519,
            "stencilRef": 0,
            "stencilFuncMask": 255,
            "stencilFail": 7680,
            "stencilZFail": 7680,
            "stencilZPass": 7680
        }
    ],
    "object": {
        "uuid": "f519deb7-229c-4df4-a8c1-54f798c2454f",
        "type": "Scene",
        "layers": 1,
        "matrix": [
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1,
            0,
            0,
            0,
            0,
            1
        ],
        "background": 0,
        "children": [
            {
                "uuid": "9f3514e7-f112-4779-bd8e-63e167b5c42b",
                "type": "Group",
                "visible": false,
                "layers": 1,
                "matrix": [
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1
                ],
                "matrixAutoUpdate": false,
                "children": [
                    {
                        "uuid": "89bb130e-d46a-464f-b148-93789c15baf9",
                        "type": "Object3D",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1
                        ]
                    },
                    {
                        "uuid": "c3a21d51-e94d-4370-bb4b-e8bfe4e9763d",
                        "type": "Line",
                        "name": "xrControllerRaycastBeam",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            100,
                            0,
                            0,
                            0,
                            0,
                            1
                        ],
                        "geometry": "dc9c8a06-8ac9-4234-9f88-836249b02e72",
                        "material": "f8d0da6c-82bb-48df-abfc-e6e5dfc33ad5"
                    }
                ]
            },
            {
                "uuid": "b3671147-685a-4461-b979-f5bb73174d60",
                "type": "Group",
                "visible": false,
                "layers": 1,
                "matrix": [
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1
                ],
                "matrixAutoUpdate": false,
                "children": [
                    {
                        "uuid": "49cd917e-ef28-4169-bea1-34e8a147db51",
                        "type": "Object3D",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1
                        ]
                    },
                    {
                        "uuid": "bfb18f85-0f89-4fd0-84c7-11d7a6763554",
                        "type": "Line",
                        "name": "xrControllerRaycastBeam",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            100,
                            0,
                            0,
                            0,
                            0,
                            1
                        ],
                        "geometry": "c29bbf60-b92a-48c4-8e8a-c2830a5976c2",
                        "material": "3420e75b-2820-448d-8170-a8b7d0e32ad2"
                    }
                ]
            },
            {
                "uuid": "9efc24f6-5040-408f-86f7-92fac72ae311",
                "type": "HemisphereLight",
                "layers": 1,
                "matrix": [
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    1,
                    0,
                    1
                ],
                "color": 16777215,
                "intensity": 3,
                "groundColor": 3100495
            },
            {
                "uuid": "f381ff12-23f8-4512-974f-c1cb0c177d5f",
                "type": "DirectionalLight",
                "layers": 1,
                "matrix": [
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    10,
                    10,
                    10,
                    1
                ],
                "color": 16777215,
                "intensity": 8,
                "shadow": {
                    "camera": {
                        "uuid": "cdb599aa-13ee-4e96-a58d-21aea0dbe5e8",
                        "type": "OrthographicCamera",
                        "layers": 1,
                        "zoom": 1,
                        "left": -5,
                        "right": 5,
                        "top": 5,
                        "bottom": -5,
                        "near": 0.5,
                        "far": 500
                    }
                }
            },
            {
                "uuid": "aad54e93-6693-40c8-84e1-6b993bdeab4c",
                "type": "Group",
                "name": "abs",
                "layers": 1,
                "matrix": [
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    -0.42697290231878493,
                    1.4580426916803302,
                    -10.312003535833327,
                    1
                ],
                "children": [
                    {
                        "uuid": "81777167-406f-4830-a256-6066bd5df489",
                        "type": "Mesh",
                        "name": "panel_abs_81777167-406f-4830-a256-6066bd5df489",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1.4,
                            0,
                            1
                        ],
                        "geometry": "29efb315-41ea-4844-95cf-c99b511a2ef6",
                        "material": "7ba73866-bc1c-48e9-aebc-21b8fa612eac"
                    },
                    {
                        "uuid": "719096d6-ca41-4fba-8662-ad2f815236d4",
                        "type": "Mesh",
                        "name": "outlet_abs_719096d6-ca41-4fba-8662-ad2f815236d4",
                        "layers": 1,
                        "matrix": [
                            0.5403023058681398,
                            0.841289028647364,
                            -0.01749824423037888,
                            0,
                            1.1102230246251565e-16,
                            0.020794827803092497,
                            0.999783764189357,
                            0,
                            0.8414709848078965,
                            -0.540185473161038,
                            0.011235493412141695,
                            0,
                            0,
                            1,
                            0.2,
                            1
                        ],
                        "geometry": "f8635ccd-1042-4638-8507-491788b9d4eb",
                        "material": "48a45bfd-b4e4-40fb-9396-956c6a0ef0a2"
                    },
                    {
                        "uuid": "9f613f66-7678-4ee0-9f42-4ee9ea8c9d7c",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            -0.3,
                            0.8,
                            0.2,
                            1
                        ],
                        "geometry": "9f067fb4-e2b1-4591-9c34-7d0b4dca72bd",
                        "material": "6C043312-8E09-4672-A15C-3F7098B184CE"
                    },
                    {
                        "uuid": "1860e6e1-685e-40ac-9e04-bb62bb8eb190",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            2.3,
                            0.2,
                            1
                        ],
                        "geometry": "46afae36-56a4-4a61-86dd-419419e50f79",
                        "material": "87BCF4B6-D465-4B74-9A16-A7CF3D784EA4"
                    },
                    {
                        "uuid": "c0223a50-5056-41d0-8ae5-4d65b5e3ae6f",
                        "type": "Mesh",
                        "name": "inlet_value_c0223a50-5056-41d0-8ae5-4d65b5e3ae6f",
                        "layers": 1,
                        "matrix": [
                            0.5403023058681398,
                            0.841289028647364,
                            -0.01749824423037888,
                            0,
                            1.1102230246251565e-16,
                            0.020794827803092497,
                            0.999783764189357,
                            0,
                            0.8414709848078965,
                            -0.540185473161038,
                            0.011235493412141695,
                            0,
                            -0.5,
                            1.8,
                            0.2,
                            1
                        ],
                        "geometry": "f8635ccd-1042-4638-8507-491788b9d4eb",
                        "material": "2b1cbc01-97cc-44e1-8ab6-a88570b0435c"
                    },
                    {
                        "uuid": "2ae7543b-1171-48a2-929a-edf046acef71",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            -0.5,
                            1.6,
                            0.2,
                            1
                        ],
                        "geometry": "d0815fe2-e5b5-467f-855a-3cbea2f52510",
                        "material": "7F3CEF16-9F08-4347-A958-006449873B87"
                    }
                ]
            },
            {
                "uuid": "40ca4510-ed99-4f08-8b1f-f6fe9bf4d0bb",
                "type": "Group",
                "name": "div",
                "layers": 1,
                "matrix": [
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    0,
                    0,
                    0,
                    1,
                    0,
                    1.6645370800078458,
                    -0.8293419266935451,
                    -10.312003535833327,
                    1
                ],
                "children": [
                    {
                        "uuid": "cc0ebee8-e449-42d3-b798-8a60931869f9",
                        "type": "Mesh",
                        "name": "panel_div_cc0ebee8-e449-42d3-b798-8a60931869f9",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            1.4,
                            0,
                            1
                        ],
                        "geometry": "367a7558-8a0f-4caa-b365-e9488ef14225",
                        "material": "2f80f1ec-2a97-45b0-ac04-992a14082790"
                    },
                    {
                        "uuid": "94860bd3-d060-4842-b5f4-11aa598de844",
                        "type": "Mesh",
                        "name": "outlet_div_94860bd3-d060-4842-b5f4-11aa598de844",
                        "layers": 1,
                        "matrix": [
                            0.5403023058681398,
                            0.841289028647364,
                            -0.01749824423037888,
                            0,
                            1.1102230246251565e-16,
                            0.020794827803092497,
                            0.999783764189357,
                            0,
                            0.8414709848078965,
                            -0.540185473161038,
                            0.011235493412141695,
                            0,
                            0,
                            1,
                            0.2,
                            1
                        ],
                        "geometry": "5e6bf299-2c64-420c-90c8-5dbda5c5b963",
                        "material": "3b9f8eb9-1ce8-4b34-9d0d-ec23b21e834e"
                    },
                    {
                        "uuid": "9ba4323b-6356-4983-a6c6-b9eb75e9e3d3",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            -0.3,
                            0.8,
                            0.2,
                            1
                        ],
                        "geometry": "0bb8aee8-ce7c-49cb-b78b-6bff7cd3458a",
                        "material": "4F801CB1-6F1F-4E17-A118-2AB694878A6B"
                    },
                    {
                        "uuid": "3f79eea3-764b-403e-be86-e4821e58fbb3",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            2.3,
                            0.2,
                            1
                        ],
                        "geometry": "43598099-f831-47b6-aac0-e61a141feb26",
                        "material": "475F0F94-92B9-4F42-BC6E-B7C81A528287"
                    },
                    {
                        "uuid": "46592c8e-35a9-4adf-bce5-3dafd3187f19",
                        "type": "Mesh",
                        "name": "inlet_value1_46592c8e-35a9-4adf-bce5-3dafd3187f19",
                        "layers": 1,
                        "matrix": [
                            0.5403023058681398,
                            0.841289028647364,
                            -0.01749824423037888,
                            0,
                            1.1102230246251565e-16,
                            0.020794827803092497,
                            0.999783764189357,
                            0,
                            0.8414709848078965,
                            -0.540185473161038,
                            0.011235493412141695,
                            0,
                            -0.5,
                            1.8,
                            0.2,
                            1
                        ],
                        "geometry": "5e6bf299-2c64-420c-90c8-5dbda5c5b963",
                        "material": "14fb8b30-e1f6-4ed1-8b44-a0a4ecd13483"
                    },
                    {
                        "uuid": "335540a5-f031-46fb-97cb-35f2a51acc5b",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            -0.5,
                            1.6,
                            0.2,
                            1
                        ],
                        "geometry": "7896c38a-10bc-469b-8f15-f29948b1a3a6",
                        "material": "F8882FE7-ADD4-467F-80D4-BDD8076E97A3"
                    },
                    {
                        "uuid": "9f67ef79-6784-4611-9af0-1a451757add8",
                        "type": "Mesh",
                        "name": "inlet_value2_9f67ef79-6784-4611-9af0-1a451757add8",
                        "layers": 1,
                        "matrix": [
                            0.5403023058681398,
                            0.841289028647364,
                            -0.01749824423037888,
                            0,
                            1.1102230246251565e-16,
                            0.020794827803092497,
                            0.999783764189357,
                            0,
                            0.8414709848078965,
                            -0.540185473161038,
                            0.011235493412141695,
                            0,
                            0.5,
                            1.8,
                            0.2,
                            1
                        ],
                        "geometry": "5e6bf299-2c64-420c-90c8-5dbda5c5b963",
                        "material": "14fb8b30-e1f6-4ed1-8b44-a0a4ecd13483"
                    },
                    {
                        "uuid": "6486dae6-dedc-4317-8bcb-5774a89a6c37",
                        "type": "Mesh",
                        "layers": 1,
                        "matrix": [
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0,
                            0,
                            0,
                            1,
                            0,
                            0.5,
                            1.6,
                            0.2,
                            1
                        ],
                        "geometry": "4cc631bb-9753-41af-bbc0-b74af65ea29e",
                        "material": "A5A05BD6-9E40-4650-AA27-35734D3DE985"
                    }
                ]
            }
        ]
    }
}

export { tempScene }